#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
. "$NVM_DIR/nvm.sh"
nvm use

echo "🔍 Running linting..."
npm run lint

echo "💅 Running prettier..."
npx prettier --write .

echo "🏗️ Building project..."
npm run build